import os
from dotenv import load_dotenv

load_dotenv()

SENDER_APP_PASSWORD = os.getenv(
    "SENDER_APP_PASSWORD"
)

OPENAI_API_KEY = os.getenv(
    "OPENAI_API_KEY"
)

FEEDBACK_SECRET_KEY = os.getenv(
    "FEEDBACK_SECRET_KEY"
)

FEEDBACK_SERVER_URL = os.getenv(
    "FEEDBACK_SERVER_URL"
)

EXTRACTOR_MODE = "ai"   # "rule" or "ai"
USE_REAL_AI = True
SHOW_MOCK_COMPARISON = False
ENABLE_FEEDBACK = False
MAX_PAPERS_TO_PROCESS = None
ENABLE_AI_IMPORTANCE = False
ENABLE_AI_NORMALIZATION = False
ENABLE_INSIGHT_GENERATION = True  # 추천된 것만
ENABLE_EMAIL_SENDING = True

SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 587

SENDER_EMAIL = "paperguide.ai@gmail.com"
SENDER_NAME = "PaperGuide AI"

# Collector settings

OPENALEX_DAYS_BACK = 14
OPENALEX_MAX_RESULTS_PER_JOURNAL = 500
OPENALEX_PAGE_SIZE = 50

PUBMED_DAYS_BACK = 1
PUBMED_MAX_TOTAL = 30
PUBMED_BATCH_SIZE = 100